from aplicacao.repositorios.repositorio_docente import RepositorioDocente
from aplicacao.repositorios.repositorio_disciplina import RepositorioDisciplina
from aplicacao.repositorios.repositorio_modulo import RepositorioModulo
from aplicacao.repositorios.repositorio_curso import RepositorioCurso
