from testes.fabricas.dominio.entidades.fabrica_teste_docente import FabricaTesteDocente
from testes.fabricas.dominio.entidades.fabrica_teste_disciplina import FabricaTesteDisciplina
from testes.fabricas.dominio.entidades.fabrica_teste_modulo import FabricaTesteModulo
from testes.fabricas.dominio.entidades.fabrica_teste_curso import FabricaTesteCurso
