from dominio.repositorios.repositorio_abstrato_docente import RepositorioAbstratoDocente
from dominio.repositorios.repositorio_abstrato_disciplina import RepositorioAbstratoDisciplina
from dominio.repositorios.repositorio_abstrato_curso import RepositorioAbstratoCurso
