from testes.fabricas.aplicacao.models.fabrica_teste_modelo_docente import FabricaTesteModeloDocente
from testes.fabricas.aplicacao.models.fabrica_teste_modelo_unidade_senai import FabricaTesteModeloUnidadeSenai
from testes.fabricas.aplicacao.models.fabrica_teste_modelo_telefone import FabricaTesteModeloTelefone
from testes.fabricas.aplicacao.models.fabrica_teste_modelo_disciplina import FabricaTesteModeloDisciplina
