from testes.fabricas.aplicacao.models.fabrica_teste_modelo_docente import FabricaTesteModeloDocente
from testes.fabricas.aplicacao.models.fabrica_teste_modelo_usuario import FabricaTesteModeloUsuario
