from testes.fabricas.dominio.otds.fabrica_teste_otd_criar_docente_entrada import FabricaTesteOTDCriarDocenteEntrada
from testes.fabricas.dominio.otds.fabrica_teste_otd_criar_docente_saida import FabricaTesteOTDCriarDocenteSaida
