from dominio.objetos_de_valor.nome_de_docente import NomeDeDocente
from dominio.objetos_de_valor.id import Id
from dominio.objetos_de_valor.nome_tipo_de_contratacao import NomeTipoDeContratacao
from dominio.objetos_de_valor.nome_de_disciplina import NomeDeDisciplina
from dominio.objetos_de_valor.numero_maior_que_zero import NumeroMaiorQueZero
from dominio.objetos_de_valor.carga_horaria import CargaHoraria
