from dominio.objetos_de_valor.carga_horaria import CargaHoraria
from dominio.objetos_de_valor.email import Email
from dominio.objetos_de_valor.id import Id
from dominio.objetos_de_valor.nome_de_curso import NomeDeCurso
from dominio.objetos_de_valor.nome_de_disciplina import NomeDeDisciplina
from dominio.objetos_de_valor.nome_de_docente import NomeDeDocente
from dominio.objetos_de_valor.nome_unidade_senai import NomeUnidadeSenai
from dominio.objetos_de_valor.numero_de_modulo import NumeroDeModulo
from dominio.objetos_de_valor.numero_maior_que_zero import NumeroMaiorQueZero
from dominio.objetos_de_valor.telefone import Telefone
from dominio.objetos_de_valor.tipo_de_contratacao import TipoDeContratacao
