from dominio.casos_de_uso.caso_de_uso_criar_docente import CasoDeUsoCriarDocente
from dominio.casos_de_uso.caso_de_uso_filtrar_docentes import CasoDeUsoFiltrarDocentes
from dominio.casos_de_uso.caso_de_uso_trazer_docente import CasoDeUsoTrazerDocente
from dominio.casos_de_uso.caso_de_uso_editar_docente import CasoDeUsoEditarDocente
