from dominio.casos_de_uso.caso_de_uso_criar_docente import CasoDeUsoCriarDocente
from dominio.casos_de_uso.caso_de_uso_trazer_docentes import CasoDeUsoTrazerDocentes
from dominio.casos_de_uso.caso_de_uso_trazer_docente import CasoDeUsoTrazerDocente
