from dominio.otds.otd_docente import OTDDocente
from dominio.otds.otd_docente_em_criacao import OTDDocenteEmCriacao
from dominio.otds.otd_disciplina import OTDDisciplina
from dominio.otds.otd_disciplina_em_criacao import OTDDisciplinaEmCriacao
from dominio.otds.otd_modulo import OTDModulo
from dominio.otds.otd_modulo_em_criacao import OTDModuloEmCriacao
from dominio.otds.otd_curso_saida import OTDCursoSaida
from dominio.otds.otd_curso_em_criacao import OTDCursoEmCriacao
from dominio.otds.otd_curso_entrada import OTDCursoEntrada
from dominio.otds.otd_competencia import OTDCompetencia
from dominio.otds.otd_caso_de_uso_editar_competencias import OTDCasoDeUsoEditarCompetencias
