from dominio.otds.otd_base import OTDBase
from dominio.otds.otd_entrada_caso_de_uso_criar_docente import OTDEntradaCasoDeUsoCriarDocente
from dominio.otds.otd_saida_caso_de_uso_criar_docente import OTDSaidaCasoDeUsoCriarDocente
