from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_id_de_docente import FabricaTesteIdDeDocente
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_nome_de_docente import FabricaTesteNomeDeDocente

from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_id_de_usuario import FabricaTesteIdDeUsuario
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_nome_de_usuario import FabricaTesteNomeDeUsuario
