# Generated by Django 4.1 on 2022-12-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocente',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_de_contratacao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloUnidadeSenai',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTelefone',
            fields=[
                ('numero', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelodocente')),
            ],
        ),
        migrations.AddField(
            model_name='modelodocente',
            name='unidade_senai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelounidadesenai'),
        ),
    ]
