# Generated by Django 4.1 on 2022-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocente',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
