# Generated by Django 4.1 on 2022-12-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCurso',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDisciplina',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.IntegerField()),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDocente',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_de_contratacao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloModulo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloUnidadeSenai',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTelefone',
            fields=[
                ('numero', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelodocente')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloModuloEmCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelocurso')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelomodulo')),
            ],
        ),
        migrations.AddField(
            model_name='modelodocente',
            name='unidade_senai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelounidadesenai'),
        ),
        migrations.CreateModel(
            name='ModeloDisciplinaEmModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelodisciplina')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelomodulo')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelodisciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelodocente')),
            ],
        ),
    ]
