# Generated by Django 4.1 on 2022-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelodocente',
            name='ativo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
