# Generated by Django 4.1 on 2022-12-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_modelodisciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCurso',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloModulo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloModuloEmCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelocurso')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelomodulo')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDisciplinaEmModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelodisciplina')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelomodulo')),
            ],
        ),
    ]
